"""Constant mixin for WhatsAppTenantConsoleService."""

from __future__ import annotations

from . import constants as c
from . import subscription_constants as sc


class _ConstMixin:
    """Holds all class-level constants for the Tenant Console service."""

    KEY_MAIN_MENU = c.KEY_MAIN_MENU
    KEY_HELP_TEXT = c.KEY_HELP_TEXT
    KEY_FALLBACK_NO_FLOW = c.KEY_FALLBACK_NO_FLOW
    KEY_FALLBACK_ACTIVE_FLOW = c.KEY_FALLBACK_ACTIVE_FLOW
    RESET_COMMANDS = c.RESET_COMMANDS
    HELP_COMMANDS = c.HELP_COMMANDS

    CLIENTS_FLOW = c.CLIENTS_FLOW
    CLIENTS_STEP_LIST = c.CLIENTS_STEP_LIST
    CLIENTS_STEP_SELECT = c.CLIENTS_STEP_SELECT
    CLIENTS_STEP_DETAIL = c.CLIENTS_STEP_DETAIL
    CLIENTS_STEP_DETAIL_ACTION = c.CLIENTS_STEP_DETAIL_ACTION
    CLIENTS_STEP_CREATE_FULL_NAME = c.CLIENTS_STEP_CREATE_FULL_NAME
    CLIENTS_STEP_CREATE_PHONE = c.CLIENTS_STEP_CREATE_PHONE
    CLIENTS_STEP_CREATE_USERNAME = c.CLIENTS_STEP_CREATE_USERNAME
    CLIENTS_STEP_CREATE_PASSWORD = c.CLIENTS_STEP_CREATE_PASSWORD
    CLIENTS_STEP_CREATE_CONFIRM = c.CLIENTS_STEP_CREATE_CONFIRM
    CLIENTS_STEP_EDIT_FIELD = c.CLIENTS_STEP_EDIT_FIELD
    CLIENTS_STEP_EDIT_VALUE = c.CLIENTS_STEP_EDIT_VALUE
    CLIENTS_STEP_DEACTIVATE_CONFIRM = c.CLIENTS_STEP_DEACTIVATE_CONFIRM
    CLIENTS_STEP_DELETE_CONFIRM = c.CLIENTS_STEP_DELETE_CONFIRM

    CATALOG_FLOW = c.CATALOG_FLOW
    CATALOG_STEP_LIST = c.CATALOG_STEP_LIST
    CATALOG_STEP_SERVICE_SELECT = c.CATALOG_STEP_SERVICE_SELECT
    CATALOG_STEP_SERVICE_DETAIL = c.CATALOG_STEP_SERVICE_DETAIL
    CATALOG_STEP_SERVICE_ACTION = c.CATALOG_STEP_SERVICE_ACTION
    CATALOG_STEP_EDIT_SERVICE = c.CATALOG_STEP_EDIT_SERVICE
    CATALOG_STEP_PLAN_SELECT = c.CATALOG_STEP_PLAN_SELECT
    CATALOG_STEP_PLAN_DETAIL = c.CATALOG_STEP_PLAN_DETAIL
    CATALOG_STEP_PLAN_ACTION = c.CATALOG_STEP_PLAN_ACTION
    CATALOG_STEP_EDIT_PLAN = c.CATALOG_STEP_EDIT_PLAN

    PROFILE_FLOW = c.PROFILE_FLOW
    PROFILE_STEP_ACTION = c.PROFILE_STEP_ACTION
    PROFILE_STEP_EDIT_FIELD = c.PROFILE_STEP_EDIT_FIELD
    PROFILE_STEP_EDIT_VALUE = c.PROFILE_STEP_EDIT_VALUE
    PROFILE_STEP_CHANGE_PASSWORD_OLD = c.PROFILE_STEP_CHANGE_PASSWORD_OLD
    PROFILE_STEP_CHANGE_PASSWORD_NEW = c.PROFILE_STEP_CHANGE_PASSWORD_NEW
    PROFILE_STEP_CHANGE_LOCALE_SELECT = c.PROFILE_STEP_CHANGE_LOCALE_SELECT

    SUBSCRIPTIONS_FLOW = c.SUBSCRIPTIONS_FLOW
    SUBSCRIPTIONS_STEP_MENU = c.SUBSCRIPTIONS_STEP_MENU
    SUBSCRIPTIONS_STEP_FILTER = c.SUBSCRIPTIONS_STEP_FILTER
    SUBSCRIPTIONS_STEP_LIST = c.SUBSCRIPTIONS_STEP_LIST
    SUBSCRIPTIONS_STEP_SELECT = c.SUBSCRIPTIONS_STEP_SELECT
    SUBSCRIPTIONS_STEP_DETAIL = c.SUBSCRIPTIONS_STEP_DETAIL
    SUBSCRIPTIONS_STEP_ACTION = c.SUBSCRIPTIONS_STEP_ACTION
    SUBSCRIPTIONS_STEP_CREATE_CLIENT = c.SUBSCRIPTIONS_STEP_CREATE_CLIENT
    SUBSCRIPTIONS_STEP_CREATE_SERVICE = c.SUBSCRIPTIONS_STEP_CREATE_SERVICE
    SUBSCRIPTIONS_STEP_CREATE_PLAN = c.SUBSCRIPTIONS_STEP_CREATE_PLAN
    SUBSCRIPTIONS_STEP_CREATE_EMAIL = c.SUBSCRIPTIONS_STEP_CREATE_EMAIL
    SUBSCRIPTIONS_STEP_CREATE_PASSWORD = c.SUBSCRIPTIONS_STEP_CREATE_PASSWORD
    SUBSCRIPTIONS_STEP_CREATE_PASSWORD_CONFIRM = c.SUBSCRIPTIONS_STEP_CREATE_PASSWORD_CONFIRM
    SUBSCRIPTIONS_STEP_CREATE_PROFILE_OPTION = c.SUBSCRIPTIONS_STEP_CREATE_PROFILE_OPTION
    SUBSCRIPTIONS_STEP_CREATE_PROFILE_NAME = c.SUBSCRIPTIONS_STEP_CREATE_PROFILE_NAME
    SUBSCRIPTIONS_STEP_CREATE_PIN = c.SUBSCRIPTIONS_STEP_CREATE_PIN
    SUBSCRIPTIONS_STEP_CREATE_PIN_CONFIRM = c.SUBSCRIPTIONS_STEP_CREATE_PIN_CONFIRM
    SUBSCRIPTIONS_STEP_CREATE_DURATION = c.SUBSCRIPTIONS_STEP_CREATE_DURATION
    SUBSCRIPTIONS_STEP_CREATE_CUSTOM_DATE = c.SUBSCRIPTIONS_STEP_CREATE_CUSTOM_DATE
    SUBSCRIPTIONS_STEP_CREATE_CONFIRM = c.SUBSCRIPTIONS_STEP_CREATE_CONFIRM
    SUBSCRIPTIONS_STEP_EDIT_FIELD = c.SUBSCRIPTIONS_STEP_EDIT_FIELD
    SUBSCRIPTIONS_STEP_EDIT_VALUE = c.SUBSCRIPTIONS_STEP_EDIT_VALUE
    SUBSCRIPTIONS_STEP_EDIT_PASSWORD_CONFIRM = c.SUBSCRIPTIONS_STEP_EDIT_PASSWORD_CONFIRM
    SUBSCRIPTIONS_STEP_EDIT_PIN_CONFIRM = c.SUBSCRIPTIONS_STEP_EDIT_PIN_CONFIRM
    SUBSCRIPTIONS_STEP_CANCEL_CONFIRM = c.SUBSCRIPTIONS_STEP_CANCEL_CONFIRM
    SUBSCRIPTIONS_STEP_REACTIVATE_DURATION = c.SUBSCRIPTIONS_STEP_REACTIVATE_DURATION
    SUBSCRIPTIONS_STEP_REACTIVATE_CUSTOM_DATE = c.SUBSCRIPTIONS_STEP_REACTIVATE_CUSTOM_DATE
    SUBSCRIPTIONS_STEP_REACTIVATE_CONFIRM = c.SUBSCRIPTIONS_STEP_REACTIVATE_CONFIRM
    SUBSCRIPTIONS_STEP_RENEW_DURATION = c.SUBSCRIPTIONS_STEP_RENEW_DURATION
    SUBSCRIPTIONS_STEP_RENEW_CUSTOM_DATE = c.SUBSCRIPTIONS_STEP_RENEW_CUSTOM_DATE
    SUBSCRIPTIONS_STEP_RENEW_CONFIRM = c.SUBSCRIPTIONS_STEP_RENEW_CONFIRM

    KEY_CLIENTS_MENU = c.KEY_CLIENTS_MENU
    KEY_CLIENT_NO_CLIENTS = c.KEY_CLIENT_NO_CLIENTS
    KEY_CLIENT_SELECT_PROMPT = c.KEY_CLIENT_SELECT_PROMPT
    KEY_CLIENT_DETAIL_ACTIVE_ACTIONS = c.KEY_CLIENT_DETAIL_ACTIVE_ACTIONS
    KEY_CLIENT_DETAIL_INACTIVE_ACTIONS = c.KEY_CLIENT_DETAIL_INACTIVE_ACTIONS
    KEY_CLIENT_CREATE_PROMPT_FULL_NAME = c.KEY_CLIENT_CREATE_PROMPT_FULL_NAME
    KEY_CLIENT_CREATE_PROMPT_PHONE = c.KEY_CLIENT_CREATE_PROMPT_PHONE
    KEY_CLIENT_CREATE_PROMPT_USERNAME = c.KEY_CLIENT_CREATE_PROMPT_USERNAME
    KEY_CLIENT_CREATE_PROMPT_PASSWORD = c.KEY_CLIENT_CREATE_PROMPT_PASSWORD
    KEY_CLIENT_CREATE_CONFIRM_TEMPLATE = c.KEY_CLIENT_CREATE_CONFIRM_TEMPLATE
    KEY_CLIENT_CREATE_SUCCESS = c.KEY_CLIENT_CREATE_SUCCESS
    KEY_CLIENT_CREATE_ERROR_PHONE = c.KEY_CLIENT_CREATE_ERROR_PHONE
    KEY_CLIENT_EDIT_FIELD_PROMPT = c.KEY_CLIENT_EDIT_FIELD_PROMPT
    CLIENT_EDIT_FIELD_MAP = c.CLIENT_EDIT_FIELD_MAP
    CLIENT_EDIT_PROMPTS = c.CLIENT_EDIT_PROMPTS
    KEY_CLIENT_EDIT_ERROR_INVALID_FIELD = c.KEY_CLIENT_EDIT_ERROR_INVALID_FIELD
    KEY_CLIENT_DEACTIVATE_CONFIRM_TEMPLATE = c.KEY_CLIENT_DEACTIVATE_CONFIRM_TEMPLATE
    KEY_CLIENT_DELETE_CONFIRM_TEMPLATE = c.KEY_CLIENT_DELETE_CONFIRM_TEMPLATE
    KEY_CLIENT_CANT_DELETE_ACTIVE = c.KEY_CLIENT_CANT_DELETE_ACTIVE
    KEY_CLIENT_DEACTIVATE_SUCCESS = c.KEY_CLIENT_DEACTIVATE_SUCCESS
    KEY_CLIENT_REACTIVATE_SUCCESS = c.KEY_CLIENT_REACTIVATE_SUCCESS
    KEY_CLIENT_DELETE_SUCCESS = c.KEY_CLIENT_DELETE_SUCCESS
    KEY_CLIENT_EDIT_SUCCESS = c.KEY_CLIENT_EDIT_SUCCESS
    KEY_CLIENT_CONFIRM_REPROMPT = c.KEY_CLIENT_CONFIRM_REPROMPT
    KEY_CLIENT_INVALID_SELECTION = c.KEY_CLIENT_INVALID_SELECTION
    KEY_CLIENT_NAME_REQUIRED = c.KEY_CLIENT_NAME_REQUIRED
    KEY_CLIENT_USERNAME_REQUIRED = c.KEY_CLIENT_USERNAME_REQUIRED
    KEY_CLIENT_SHORT_PASSWORD = c.KEY_CLIENT_SHORT_PASSWORD
    CLIENT_SKIP_WORDS = c.CLIENT_SKIP_WORDS

    KEY_CATALOG_MENU = c.KEY_CATALOG_MENU
    KEY_CATALOG_NO_SERVICES = c.KEY_CATALOG_NO_SERVICES
    KEY_CATALOG_SERVICE_PROMPT = c.KEY_CATALOG_SERVICE_PROMPT
    KEY_CATALOG_SERVICE_ACTIONS = c.KEY_CATALOG_SERVICE_ACTIONS
    KEY_CATALOG_SERVICE_EDIT_PROMPT = c.KEY_CATALOG_SERVICE_EDIT_PROMPT
    KEY_CATALOG_SERVICE_EDIT_SUCCESS = c.KEY_CATALOG_SERVICE_EDIT_SUCCESS
    KEY_CATALOG_PLAN_ACTIONS = c.KEY_CATALOG_PLAN_ACTIONS
    KEY_CATALOG_NO_PLANS = c.KEY_CATALOG_NO_PLANS
    KEY_CATALOG_PLAN_PROMPT = c.KEY_CATALOG_PLAN_PROMPT
    KEY_CATALOG_PLAN_EDIT_PROMPT = c.KEY_CATALOG_PLAN_EDIT_PROMPT
    KEY_CATALOG_PLAN_EDIT_SUCCESS = c.KEY_CATALOG_PLAN_EDIT_SUCCESS
    KEY_CATALOG_INVALID_SELECTION = c.KEY_CATALOG_INVALID_SELECTION
    KEY_CATALOG_NAME_REQUIRED = c.KEY_CATALOG_NAME_REQUIRED

    KEY_PROFILE_MENU = c.KEY_PROFILE_MENU
    KEY_PROFILE_EDIT_FIELD_PROMPT = c.KEY_PROFILE_EDIT_FIELD_PROMPT
    PROFILE_EDIT_FIELD_MAP = c.PROFILE_EDIT_FIELD_MAP
    PROFILE_EDIT_PROMPTS = c.PROFILE_EDIT_PROMPTS
    KEY_PROFILE_EDIT_ERROR_INVALID_FIELD = c.KEY_PROFILE_EDIT_ERROR_INVALID_FIELD
    KEY_PROFILE_EDIT_SUCCESS = c.KEY_PROFILE_EDIT_SUCCESS
    KEY_PROFILE_CHANGE_PASSWORD_PROMPT_OLD = c.KEY_PROFILE_CHANGE_PASSWORD_PROMPT_OLD
    KEY_PROFILE_CHANGE_PASSWORD_PROMPT_NEW = c.KEY_PROFILE_CHANGE_PASSWORD_PROMPT_NEW
    KEY_PROFILE_CHANGE_PASSWORD_ERROR_OLD = c.KEY_PROFILE_CHANGE_PASSWORD_ERROR_OLD
    KEY_PROFILE_CHANGE_PASSWORD_SUCCESS = c.KEY_PROFILE_CHANGE_PASSWORD_SUCCESS
    KEY_PROFILE_LOCALE_SELECT = c.KEY_PROFILE_LOCALE_SELECT

    KEY_SUBSCRIPTIONS_MENU = sc.KEY_SUBSCRIPTIONS_MENU
    KEY_SUBSCRIPTIONS_FILTER_PROMPT = sc.KEY_SUBSCRIPTIONS_FILTER_PROMPT
    KEY_SUBSCRIPTIONS_NO_RESULTS = sc.KEY_SUBSCRIPTIONS_NO_RESULTS
    KEY_SUBSCRIPTIONS_SELECT_PROMPT = sc.KEY_SUBSCRIPTIONS_SELECT_PROMPT
    KEY_SUBSCRIPTION_DETAIL_ACTIONS = sc.KEY_SUBSCRIPTION_DETAIL_ACTIONS
    KEY_SUBSCRIPTION_DETAIL_ACTIONS_ACTIVE = sc.KEY_SUBSCRIPTION_DETAIL_ACTIONS_ACTIVE
    KEY_SUBSCRIPTIONS_CREATE_CLIENT_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_CLIENT_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_SERVICE_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_SERVICE_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PLAN_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_PLAN_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_EMAIL_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_EMAIL_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PASSWORD_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_PASSWORD_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PASSWORD_CONFIRM_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_PASSWORD_CONFIRM_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PASSWORD_MISMATCH = sc.KEY_SUBSCRIPTIONS_CREATE_PASSWORD_MISMATCH
    KEY_SUBSCRIPTIONS_CREATE_PROFILE_NAME_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_PROFILE_NAME_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PROFILE_OPTION_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_PROFILE_OPTION_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PIN_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_PIN_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PIN_CONFIRM_PROMPT = sc.KEY_SUBSCRIPTIONS_CREATE_PIN_CONFIRM_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_PIN_MISMATCH = sc.KEY_SUBSCRIPTIONS_CREATE_PIN_MISMATCH
    KEY_SUBSCRIPTIONS_CREATE_PIN_REQUIRES_PROFILE = sc.KEY_SUBSCRIPTIONS_CREATE_PIN_REQUIRES_PROFILE
    KEY_SUBSCRIPTIONS_DURATION_PROMPT = sc.KEY_SUBSCRIPTIONS_DURATION_PROMPT
    KEY_SUBSCRIPTIONS_CUSTOM_DATE_PROMPT = sc.KEY_SUBSCRIPTIONS_CUSTOM_DATE_PROMPT
    KEY_SUBSCRIPTIONS_CREATE_CONFIRM_TEMPLATE = sc.KEY_SUBSCRIPTIONS_CREATE_CONFIRM_TEMPLATE
    KEY_SUBSCRIPTIONS_CREATE_SUCCESS = sc.KEY_SUBSCRIPTIONS_CREATE_SUCCESS
    KEY_SUBSCRIPTIONS_EDIT_FIELD_PROMPT = sc.KEY_SUBSCRIPTIONS_EDIT_FIELD_PROMPT
    KEY_SUBSCRIPTIONS_EDIT_ERROR_INVALID_FIELD = sc.KEY_SUBSCRIPTIONS_EDIT_ERROR_INVALID_FIELD
    KEY_SUBSCRIPTIONS_EDIT_SUCCESS = sc.KEY_SUBSCRIPTIONS_EDIT_SUCCESS
    KEY_SUBSCRIPTIONS_EDIT_PASSWORD_CONFIRM_PROMPT = sc.KEY_SUBSCRIPTIONS_EDIT_PASSWORD_CONFIRM_PROMPT
    KEY_SUBSCRIPTIONS_EDIT_PIN_CONFIRM_PROMPT = sc.KEY_SUBSCRIPTIONS_EDIT_PIN_CONFIRM_PROMPT
    KEY_SUBSCRIPTIONS_EDIT_MISMATCH = sc.KEY_SUBSCRIPTIONS_EDIT_MISMATCH
    KEY_SUBSCRIPTIONS_CANCEL_CONFIRM_TEMPLATE = sc.KEY_SUBSCRIPTIONS_CANCEL_CONFIRM_TEMPLATE
    KEY_SUBSCRIPTIONS_CANCEL_SUCCESS = sc.KEY_SUBSCRIPTIONS_CANCEL_SUCCESS
    KEY_SUBSCRIPTIONS_REACTIVATE_DURATION_PROMPT = sc.KEY_SUBSCRIPTIONS_REACTIVATE_DURATION_PROMPT
    KEY_SUBSCRIPTIONS_REACTIVATE_CUSTOM_DATE_PROMPT = sc.KEY_SUBSCRIPTIONS_REACTIVATE_CUSTOM_DATE_PROMPT
    KEY_SUBSCRIPTIONS_REACTIVATE_CONFIRM_TEMPLATE = sc.KEY_SUBSCRIPTIONS_REACTIVATE_CONFIRM_TEMPLATE
    KEY_SUBSCRIPTIONS_REACTIVATE_SUCCESS = sc.KEY_SUBSCRIPTIONS_REACTIVATE_SUCCESS
    KEY_SUBSCRIPTIONS_RENEW_DURATION_PROMPT = sc.KEY_SUBSCRIPTIONS_RENEW_DURATION_PROMPT
    KEY_SUBSCRIPTIONS_RENEW_CUSTOM_DATE_PROMPT = sc.KEY_SUBSCRIPTIONS_RENEW_CUSTOM_DATE_PROMPT
    KEY_SUBSCRIPTIONS_RENEW_CONFIRM_TEMPLATE = sc.KEY_SUBSCRIPTIONS_RENEW_CONFIRM_TEMPLATE
    KEY_SUBSCRIPTIONS_RENEW_SUCCESS = sc.KEY_SUBSCRIPTIONS_RENEW_SUCCESS
    KEY_SUBSCRIPTIONS_INVALID_SELECTION = sc.KEY_SUBSCRIPTIONS_INVALID_SELECTION
    KEY_SUBSCRIPTIONS_CONFIRM_REPROMPT = sc.KEY_SUBSCRIPTIONS_CONFIRM_REPROMPT
    KEY_SUBSCRIPTIONS_EMAIL_REQUIRED = sc.KEY_SUBSCRIPTIONS_EMAIL_REQUIRED
    KEY_SUBSCRIPTIONS_CLIENT_REQUIRED = sc.KEY_SUBSCRIPTIONS_CLIENT_REQUIRED
    SUBSCRIPTIONS_SKIP_WORDS = sc.SUBSCRIPTIONS_SKIP_WORDS
    SUBSCRIPTIONS_DURATION_MAP = sc.SUBSCRIPTIONS_DURATION_MAP
    SUBSCRIPTIONS_EDIT_FIELD_MAP = sc.SUBSCRIPTIONS_EDIT_FIELD_MAP
    SUBSCRIPTIONS_EDIT_PROMPT_KEYS = sc.SUBSCRIPTIONS_EDIT_PROMPT_KEYS
