/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoEndedRouteImport } from './routes/demo-ended'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterExecutorsRouteImport } from './routes/master/executors'
import { Route as MasterDashboardRouteImport } from './routes/master/dashboard'
import { Route as ClientProfileRouteImport } from './routes/client/profile'
import { Route as ClientHelpRouteImport } from './routes/client/help'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminHelpRouteImport } from './routes/admin/help'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AdminDemoSimulatorRouteImport } from './routes/admin/demo/simulator'

const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEndedRoute = DemoEndedRouteImport.update({
  id: '/demo-ended',
  path: '/demo-ended',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterExecutorsRoute = MasterExecutorsRouteImport.update({
  id: '/executors',
  path: '/executors',
  getParentRoute: () => MasterRoute,
} as any)
const MasterDashboardRoute = MasterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MasterRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientHelpRoute = ClientHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoSimulatorRoute = AdminDemoSimulatorRouteImport.update({
  id: '/demo/simulator',
  path: '/demo/simulator',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/demo-ended': typeof DemoEndedRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/help': typeof ClientHelpRoute
  '/client/profile': typeof ClientProfileRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/executors': typeof MasterExecutorsRoute
  '/admin/demo/simulator': typeof AdminDemoSimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/demo-ended': typeof DemoEndedRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/help': typeof ClientHelpRoute
  '/client/profile': typeof ClientProfileRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/executors': typeof MasterExecutorsRoute
  '/admin/demo/simulator': typeof AdminDemoSimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/demo-ended': typeof DemoEndedRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/help': typeof ClientHelpRoute
  '/client/profile': typeof ClientProfileRoute
  '/master/dashboard': typeof MasterDashboardRoute
  '/master/executors': typeof MasterExecutorsRoute
  '/admin/demo/simulator': typeof AdminDemoSimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/demo-ended'
    | '/login'
    | '/master'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/client/dashboard'
    | '/client/help'
    | '/client/profile'
    | '/master/dashboard'
    | '/master/executors'
    | '/admin/demo/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/demo-ended'
    | '/login'
    | '/master'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/client/dashboard'
    | '/client/help'
    | '/client/profile'
    | '/master/dashboard'
    | '/master/executors'
    | '/admin/demo/simulator'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/demo-ended'
    | '/login'
    | '/master'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/help'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/client/dashboard'
    | '/client/help'
    | '/client/profile'
    | '/master/dashboard'
    | '/master/executors'
    | '/admin/demo/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  DemoEndedRoute: typeof DemoEndedRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-ended': {
      id: '/demo-ended'
      path: '/demo-ended'
      fullPath: '/demo-ended'
      preLoaderRoute: typeof DemoEndedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/executors': {
      id: '/master/executors'
      path: '/executors'
      fullPath: '/master/executors'
      preLoaderRoute: typeof MasterExecutorsRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/dashboard': {
      id: '/master/dashboard'
      path: '/dashboard'
      fullPath: '/master/dashboard'
      preLoaderRoute: typeof MasterDashboardRouteImport
      parentRoute: typeof MasterRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/help': {
      id: '/client/help'
      path: '/help'
      fullPath: '/client/help'
      preLoaderRoute: typeof ClientHelpRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo/simulator': {
      id: '/admin/demo/simulator'
      path: '/demo/simulator'
      fullPath: '/admin/demo/simulator'
      preLoaderRoute: typeof AdminDemoSimulatorRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminDemoSimulatorRoute: typeof AdminDemoSimulatorRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminDemoSimulatorRoute: AdminDemoSimulatorRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientHelpRoute: typeof ClientHelpRoute
  ClientProfileRoute: typeof ClientProfileRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientHelpRoute: ClientHelpRoute,
  ClientProfileRoute: ClientProfileRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface MasterRouteChildren {
  MasterDashboardRoute: typeof MasterDashboardRoute
  MasterExecutorsRoute: typeof MasterExecutorsRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterDashboardRoute: MasterDashboardRoute,
  MasterExecutorsRoute: MasterExecutorsRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  DemoEndedRoute: DemoEndedRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
